name: FacingTime
options:
  bundleIdPrefix: com.facingtime
  deploymentTarget:
    iOS: "16.0"
    macOS: "13.0"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic

targets:
  FacingTimeTests_iOS:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Sources/UnitTests
        type: group
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.facingtime.tests
        GENERATE_INFOPLIST_FILE: true
    dependencies:
      - target: FacingTime_iOS

  FacingTimeTests_macOS:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Sources/UnitTests
        type: group
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.facingtime.tests
        GENERATE_INFOPLIST_FILE: true
    dependencies:
      - target: FacingTime_macOS

  FacingTime_iOS:
    type: application
    platform: iOS
    sources:
      - path: Sources
        excludes:
          - "UnitTests/**"
          - "RustCore/**"
        type: group
      - path: Resources
        type: group
      - path: README.md
        type: file
        buildPhase: resources
    settings:
      base:
        INFOPLIST_FILE: Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.facingtime.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: false
        SUPPORTS_MACCATALYST: false
        TARGETED_DEVICE_FAMILY: "1,2"
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
    info:
      path: Resources/Info.plist
      properties:
        CFBundleName: "$(PRODUCT_NAME)"
        CFBundleDisplayName: "FacingTime"
        CFBundleIdentifier: "$(PRODUCT_BUNDLE_IDENTIFIER)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleExecutable: "$(EXECUTABLE_NAME)"
        CFBundlePackageType: "$(PRODUCT_BUNDLE_PACKAGE_TYPE)"
        LSMinimumSystemVersion: "$(MACOSX_DEPLOYMENT_TARGET)"
        UILaunchScreen:
          UIColorName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSLocalNetworkUsageDescription: "需要访问本地网络以发现附近的设备并进行通讯"
        NSBonjourServices:
          - "_facingtime._tcp"

  FacingTime_macOS:
    type: application
    platform: macOS
    sources:
      - path: Sources
        excludes:
          - "UnitTests/**"
          - "RustCore/**"
        type: group
      - path: Resources
        type: group
      - path: README.md
        type: file
        buildPhase: resources
    settings:
      base:
        INFOPLIST_FILE: Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.facingtime.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: false
        SUPPORTS_MACCATALYST: false
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
    info:
      path: Resources/Info.plist
      properties:
        CFBundleName: "$(PRODUCT_NAME)"
        CFBundleDisplayName: "FacingTime"
        CFBundleIdentifier: "$(PRODUCT_BUNDLE_IDENTIFIER)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleExecutable: "$(EXECUTABLE_NAME)"
        CFBundlePackageType: "$(PRODUCT_BUNDLE_PACKAGE_TYPE)"
        LSMinimumSystemVersion: "$(MACOSX_DEPLOYMENT_TARGET)"
        NSLocalNetworkUsageDescription: "需要访问本地网络以发现附近的设备并进行通讯"
        NSBonjourServices:
          - "_facingtime._tcp"

schemes:
  FacingTime_iOS:
    build:
      targets:
        FacingTime_iOS: all
        FacingTimeTests_iOS: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - FacingTimeTests_iOS
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  FacingTime_macOS:
    build:
      targets:
        FacingTime_macOS: all
        FacingTimeTests_macOS: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - FacingTimeTests_macOS
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
